### ISSUE TITLE
Invalid

### ISSUE THREAD

**Issue by dirtyballoonot** [tajnymag/tinder-deblur#39]
![image](https://github.com/tajnymag/tinder-deblur/assets/103008191/3c64207a-2c58-4c65-88ad-b33e9fdc59f6)

**Comment by JustixDevelopment** [comment]
"invalid" means that the image cannot be unblurred because it doesn't contain the user id.

Please send the response of "https://api.gotinder.com/v2/fast-match/teasers" (have a look at the network tab in the dev tools) and the url of the image (via inspect element and then copy the value for the css property 'background-image'). You can ofcourse send this to me on a more private way (Discord: Justix#7918 or email: admin@justix-dev.com) and you should also remove all other likes if you want to keep your likes private!

**Comment by dirtyballoonot** [comment]
I'll get to that sure...Not sure I understand.  Why would I care about keeping my "likes" private?  I'm pretty sure the chicks here in Brasil are not that saavy. What I REALLY need is a bulk messenger.  Only one Chinese app works anymore, but, I'm stuck in their billing app limbo, lol  The comment from the last post with the new API seems to partially work

**Comment by dirtyballoonot** [comment]
> "invalid" means that the image cannot be unblurred because it doesn't contain the user id.
> 
> Please send the response of "https://api.gotinder.com/v2/fast-match/teasers" (have a look at the network tab in the dev tools) and the url of the image (via inspect element and then copy the value for the css property 'background-image'). You can ofcourse send this to me on a more private way (Discord: Justix#7918 or email: [admin@justix-dev.com](mailto:admin@justix-dev.com)) and you should also remove all other likes if you want to keep your likes private!

Sent you a DM
